### ISSUE TITLE
SoftwarePack.exe打不开

### ISSUE THREAD

**Issue by yhb1319170996** [micahh28/HHSoftwarePack#2]
感觉挺好用的，但是。这个主程序点击打开无响应，我要配置什么东西吗？

**Comment by Chadwuo** [comment]
抱歉，这是一个失误。
如何解决：
请将 项目根目录下的packages/SevenZipSharp.Interop.19.0.1/build 这个路径下两个文件夹【x64】、【x86】手动拷贝至 debug目录中

**Comment by yhb1319170996** [comment]
> 抱歉，这是一个项目的根目录。如何解决这个问题 ： 不同的项目目录/SevenZipSharp.Interop.19.1/build 路径文件夹【x64】、【x86】手动复制到debug中

![image](https://user-images.githubusercontent.com/56821681/185522181-24a5d224-bb35-44ab-871f-588bcd51c02a.png)
我在这些文件里面没有找到你所说的这些目录（/SevenZipSharp.Interop.19.1/build，debug），我下载的文件似乎跟你描述的不太一样

**Comment by Chadwuo** [comment]
release.zip下载后，是可以直接运行的。

**Comment by yhb1319170996** [comment]
![image](https://user-images.githubusercontent.com/56821681/185523896-d4a9a0f4-406c-4402-bf25-781b68068836.png)
是的，我完整的下载了release.zip，但是我打开SoftwarePack.exe无任何响应

**Comment by Chadwuo** [comment]
真是费解，我确认了一下，文件是对的。你是什么操作系统呢

**Comment by yhb1319170996** [comment]
> 真是费解，我确认了，文件是对的。你是什么角色呢

哈哈，好吧，我是win11，我用其他电脑试试

**Comment by yhb1319170996** [comment]
> 真是费解，我确认了，文件是对的。你是什么角色呢

谢谢，可能是我电脑的一些原因

**Comment by Chadwuo** [comment]
> > 真是费解，我确认了，文件是对的。你是什么角色呢
> 
> 谢谢，可能是我电脑的一些原因

好的
