### ISSUE TITLE
为何打包时生成的是skin.zip ,能把打包的批处理命令换换吗

### ISSUE THREAD

**Issue by beikee** [micahh28/HHSoftwarePack#3]
批处理文件是个skin.zip 的

**Comment by Chadwuo** [comment]
> 批处理文件是个skin.zip 的

忘记了，好久前写的，做的不好给您添堵了。我看了一下，skin.zip是安装卸载界面文件。这个程序做的事情，就是自定义图片、名称，然后生成新的skin文件，交给脚本命令。

**Comment by beikee** [comment]
好像没啥问题,换我电脑上能生成了,可能是我同事电脑目录等有问题,感谢回答
